# For more information: https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"
services:

  wp:
    build:
      context: ./docker/wp-6.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: kimael-code/wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${DB_USERNAME}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD:-secret}"
      WORDPRESS_DB_NAME: "${DB_DATABASE}"
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - "wordpress:/var/www/html"
    networks:
      - localdev
    depends_on:
      - db

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
      MARIADB_DATABASE: "${DB_DATABASE:-wordpress}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD:-secret}"
    ports:
      - "3306:3306"
    volumes:
      - "localdev-mariadb:/var/lib/mysql"
    networks:
      - localdev

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - localdev

networks:
  localdev:

volumes:
  wordpress:
  localdev-mariadb:
